/*POKEMON ACTION TYPES*/
export const SELECTED_POKEMON = 'SELECTED_POKEMON';
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR';
export const ADD_POKEMON_REQUEST = 'ADD_POKEMON_REQUEST';
export const ADD_POKEMON_SUCCESS = 'ADD_POKEMON_SUCCESS';
export const ADD_POKEMON_ERROR = 'ADD_POKEMON_ERROR';
export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR';

/*UI ACTION TYPES*/
export const UI_UPDATE_PAGINATION = 'UI_UPDATE_PAGINATION';
export const UI_TOGGLE_SHOW_POPUP = 'UI_TOGGLE_SHOW_POPUP';
