/*POKEMON ACTION TYPES*/
export const SELECTED_POKEMON = 'SELECTED_POKEMON';
export const FETCH_POKEMON_REQUEST = 'FETCH_POKEMON_REQUEST';
export const FETCH_POKEMON_SUCCESS = 'FETCH_POKEMON_SUCCESS';
export const FETCH_POKEMON_ERROR = 'FETCH_POKEMON_ERROR';
export const ADD_POKEMON_REQUEST = 'ADD_POKEMON_REQUEST';
export const ADD_POKEMON_SUCCESS = 'ADD_POKEMON_SUCCESS';
export const ADD_POKEMON_ERROR = 'ADD_POKEMON_ERROR';
export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_ERROR = 'GET_POKEMON_ERROR';

export const GET_POKEMON_EVO_CHAIN_SUCCESS = 'GET_POKEMON_EVO_CHAIN_SUCCESS';
export const GET_POKEMON_ABILITY_SUCCESS = 'GET_POKEMON_ABILITY_SUCCESS';
export const GET_POKEMON_TYPE_SUCCESS = 'GET_POKEMON_TYPE_SUCCESS';
export const GET_POKEMON_SPECIES_SUCCESS = 'GET_POKEMON_SPECIES_SUCCESS';

export const POKEMON_SPRITE_ERROR = 'POKEMON_SPRITE_ERROR';
export const POKEMON_IMAGE_ERROR = 'POKEMON_IMAGE_ERROR';
/*UI ACTION TYPES*/
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION';
export const TOGGLE_SHOW_POPUP = 'TOGGLE_SHOW_POPUP';
export const LIST_MODE_CHANGE = 'LIST_MODE_CHANGE';
export const SEARCH_PAYLOAD_CHANGE = 'SEARCH_PAYLOAD_CHANGE';
export const SELECTED_PAYLOAD_LIST = 'SELECTED_PAYLOAD_LIST';
export const FETCH_PAYLOAD_LIST_REQUEST = 'FETCH_PAYLOAD_LIST_REQUEST';
export const FETCH_PAYLOAD_LIST_SUCCESS = 'FETCH_PAYLOAD_LIST_SUCCESS';
export const FETCH_PAYLOAD_LIST_ERROR = 'FETCH_PAYLOAD_LIST_ERROR';
